apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- external-secrets/cluster-secret-store.yaml
- external-secrets/rds-externalsecret.yaml
images:
- name: cartservice
  newName: 962765735385.dkr.ecr.ap-southeast-1.amazonaws.com/mini-ecommerce/cartservice
  newTag: 7e5d6dc8f46dee3a5c1d3c881b5b3854d28179c5
- name: checkoutservice
  newName: 962765735385.dkr.ecr.ap-southeast-1.amazonaws.com/mini-ecommerce/checkoutservice
  newTag: 7e5d6dc8f46dee3a5c1d3c881b5b3854d28179c5
- name: frontend
  newName: 962765735385.dkr.ecr.ap-southeast-1.amazonaws.com/mini-ecommerce/frontend
  newTag: 7e5d6dc8f46dee3a5c1d3c881b5b3854d28179c5
- name: productcatalogservice
  newName: 962765735385.dkr.ecr.ap-southeast-1.amazonaws.com/mini-ecommerce/productcatalogservice
  newTag: 7e5d6dc8f46dee3a5c1d3c881b5b3854d28179c5
